# Generated by Django 4.2.7 on 2023-11-28 20:45

from django.db import migrations, models
import django.db.models.deletion
import post_and_comments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0003_userprofile_followers_userprofile_following"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=post_and_comments.models.post_image,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="user.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
