# Generated by Django 4.2.7 on 2023-12-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post_and_comments", "0002_like_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes+",
                to="post_and_comments.post",
            ),
        ),
    ]
