# Generated by Django 4.2.7 on 2023-12-12 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_userprofile_followers_userprofile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="following",
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to="user.follow"
            ),
        ),
    ]
