# Generated by Django 4.2.7 on 2023-12-12 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
